services:
 redis:
  image: redis:7.4
  restart: unless-stopped
  ports:
   - "127.0.0.1:6379:6379"
  command: redis-server /usr/local/etc/redis/redis.conf
  volumes:
   - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
  ulimits:
   nproc: 65535
   nofile:
    soft: 65535
    hard: 65535
  deploy:
   resources:
    limits:
     cpus: "4"
     memory: 25G
    reservations:
     cpus: "2"
     memory: 4G
  networks:
   - default

 cache:
  build:
   context: .
   dockerfile: cache.Dockerfile
  restart: unless-stopped
  networks:
   - default
  depends_on:
   - redis
   - nirn

 website:
  build:
   context: .
   dockerfile: website.Dockerfile
  restart: unless-stopped
  ports:
   - "0.0.0.0:5173:5173"
  networks:
   - default
  depends_on:
   - redis
   - nirn

networks:
 default:
  driver: bridge
