global:
  scrape_interval: 5s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: 'nirn'
    static_configs:
      - targets: ['nirn:9000']

  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]
      
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']